# Generated by Django 4.0.3 on 2022-05-07 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Team', '0002_request'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='accepted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='request',
            name='declined',
            field=models.BooleanField(default=False),
        ),
    ]
